version: '3.8'

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge

services:
  api-gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-ecommerce
    restart: always
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ecommerce-network

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:24.0.1
      command: [ "start-dev", "--import-realm" ]
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8181:8080"
      volumes:
        - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      depends_on:
        - keycloak-mysql