version: '4'

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
      MYSQL_USER: inventoryuser
      MYSQL_PASSWORD: inventorypassword
    ports:
      - "3307:3306"
    volumes:
      - E:/docker-volumes/inventory-service/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 30s
      retries: 10
      start_period: 30s
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--max_connections=200',
      '--wait_timeout=300',
      '--interactive_timeout=300'
    ]

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_service?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: inventoryuser
      SPRING_DATASOURCE_PASSWORD: inventorypassword
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_FLYWAY_ENABLED: "true"
    networks:
      - ecommerce-network